---
title: "ACE Project continuous"
author: "Caleb"
date: "`r Sys.Date()`"
output:
  html_document: default
  pdf_document: default
editor_options: 
  markdown: 
    wrap: 72
---

## Load trees

```{R}
library(treats)
trees <- read.tree("../Data/trees/simulated.tre")
bd_params <- make.bd.params(speciation = 1, extinction = 0.7)

stop_rule <- list(max.living = 50)
set.seed(123)
trees <- treats(stop.rule = stop_rule, bd.params = bd_params, null.error = 100, replicates = 5)
```


## Now simulating continuous characters

```{r}
## BM process

source("../Functions/fossil.pres.R")

bm <- make.traits(process = BM.process, n = 20)
ou <- make.traits(process = OU.process, n = 20)
# random_cont <- make.traits(process = no.process, n = 100)

bm_matrices <- lapply(trees, function(tree){
    mapped <- map.traits(bm, tree)
    matrix <- mapped$data
    return(matrix)
})
ou_matrices <- lapply(trees, function(tree){
    mapped <- map.traits(ou, tree)
    matrix <- mapped$data
    return(matrix)
})
# random_cont_matrices <- lapply(trees, function(tree){
#     mapped <- map.traits(random_cont, tree)
#     matrix <- mapped$data
#     return(matrix)
# })

continuous_matrices <- list(bm = bm_matrices, ou = ou_matrices)


saveRDS(continuous_matrices, "../Data/matrices/continuous/contmatrices.Rds")
continuous_matrices <- readRDS("../Data/matrices/continuous/contmatrices.Rds")

living_cont <- lapply(continuous_matrices, remove.fossil, trees = trees, type = "continuous")
fossilised_high_cont <- lapply(continuous_matrices, fossil.pres, trees = trees, preservation = 0.5, type = "continuous")
fossilised_med_cont <- lapply(continuous_matrices, fossil.pres, trees = trees, preservation = 0.15, type = "continuous")
fossilised_low_cont <- lapply(continuous_matrices, fossil.pres, trees = trees, preservation = 0.05, type = "continuous")
all_fossil <- lapply(continuous_matrices, fossil.pres, trees = trees, preservation = 1.0, type = "continuous")

fossil_levels_cont <- list(all = all_fossil, fossil_high = fossilised_high_cont, fossil_med = fossilised_med_cont, fossil_low = fossilised_low_cont, living = living_cont)

fossil_matrices_cont <- lapply(names(continuous_matrices), function(level) {
  lapply(seq_along(continuous_matrices[[level]]), function(i) {
    list(
      all = all_fossil[[level]][[i]],
      fossil_high = fossilised_high_cont[[level]][[i]],
      fossil_med = fossilised_med_cont[[level]][[i]],
      fossil_low = fossilised_low_cont[[level]][[i]],
      living = living_cont[[level]][[i]]
    )
  })
})
names(fossil_matrices_cont) <- names(continuous_matrices)


```

## Continuous pipeline

```{r}

# traitspace_cont <- pca.func(continuous_matrices)

# disp_obj_cont <- lapply(traitspace_cont, make.dispRity, tree = tree)


# time_sliced_cont <- lapply(disp_obj_cont, do.time.slice, chrono_models = chrono_models, time_interval = 10)

# bootstrapped_cont <- lapply(time_sliced_cont, lapply, boot.matrix, bootstraps = 100)

# disparity_cont <- lapply(bootstrapped_cont, lapply,  dispRity, metric = c(sum, variances), na.rm = TRUE, verbose = TRUE)

# saveRDS(disparity_cont, "../Data/processed/disparity/aceproject/beckcont.Rds")
# saveRDS(disparity_cont, "../Data/processed/disparity/aceproject/simcont.Rds")


# plot(disparity_cont$ou$proximity)

```

## Post ordination ace

```{R}

tip_matrices <- lapply(fossil_matrices_cont, lapply, lapply, function(matrices){
  tree <- matrices$tree
  prune <- matrices$matrix[grepl("^t", rownames(matrices$matrix)), ]
  return(list(matrix = prune, tree = tree))
})

ord_tips <- lapply(tip_matrices, lapply, lapply, function(matrix){
  tree <- matrix$tree
  ord <- (prcomp(matrix$matrix, center = TRUE, scale. = TRUE))$x
  return(list(matrix = ord, tree = tree))
})


anc_post_ord <- lapply(ord_tips, anc.states)
saveRDS(anc_post_ord, "~/Documents/PhD/largefiles/acedisparity/postordcontanc.Rds")





```




## ace continuous

```{r}

# test <- multi.ace(fossil_matrices_cont$bm$fossil_med[[1]]$matrix, fossil_matrices_cont$bm$fossil_med[[1]]$tree, models = 
n_cores <- min(detectCores() - 1, 6)
anc.states <- function(fossil_matrices_cont){
  lapply(fossil_matrices_cont, function(level){
    lapply(level, function(x) {
  # Run multi.ace for each tree
  anc_states <- multi.ace(data = x$matrix, 
                          tree = x$tree, 
                          models = "BM", 
                          output = "multi.ace",
                          parallel = n_cores,
                          verbose = TRUE)
  return(anc_states)})})}


fossil_anc <- lapply(fossil_matrices_cont, anc.states)
# test_anc <- lapply(fossil_matrices_cont, anc.states)
saveRDS(fossil_anc, "../Data/matrices/continuous/contanc.Rds")
fossil_anc <- readRDS("../Data/matrices/continuous/contanc.Rds")

normal_sampling <- list(fun = rnorm, param = list(mean = mean, sd = function(x)return(diff(range(x))/4)))

sample_fossil_anc <- lapply(fossil_anc, lapply, lapply,  multi.ace, sample = 100, sample.fun = normal_sampling, output = "combined.matrix")

point_fossil_anc <- lapply(fossil_anc, lapply, lapply,  multi.ace,  output = "combined.matrix")



str(test_anc)

```

## Measure raw euclidean distance

```{R}

get.living.nodes <- function(living) {
  if (inherits(living$living, "list")) {
  matrix <- living$living[[1]]
  } else {
  matrix <- living$living}
  node_v <- rownames(matrix)[grepl("^n", rownames(matrix))]
  return(node_v)
}


node_labels <- lapply(sample_fossil_anc$bm, get.living.nodes)

# filter.nodes <- function(true, ace, node_v) {
#   ace_filtered <- ace[node_v, , drop = FALSE]
#   return(list(ace = ace_filtered))
# }

# nodes_living <- function(true_matrices, aced_matrices) {
#   output <- lapply(names(true_matrices), function(i) {

#     # Step 1: Get node names from "living" ACE
#     living_node <- get.living.nodes(
#       living = aced_matrices$living[[i]]
#     )

#     # Step 2: For the current level, filter all preservation states
#     filtered_preservations <- lapply(names(aced_matrices), function(pres) {
#       lapply(seq_along(aced_matrices[[pres]][[i]]), function(j) {
#         filter.nodes(
#           true = true_matrices[[i]],
#           ace = aced_matrices[[pres]][[i]][[j]],
#           node_v = living_node
#         )
#       })
#     })
#     names(filtered_preservations) <- names(aced_matrices)
#     return(filtered_preservations)
#   })

#   names(output) <- names(true_matrices)
#   return(output)
# }


sample_living_nodes <- lapply(seq_along(sample_fossil_anc), function(rate) {
  lapply(seq_along(sample_fossil_anc[[rate]]), function(i) {
    # Step 1: Compute the true matrix once for the current replicate (i)
    node_v <- node_labels[[i]]
    true <- continuous_matrices[[rate]][[i]][node_v, ]

    # Step 2: Iterate over preservation levels
    levels <- names(sample_fossil_anc[[rate]][[i]])
    ace_out <- lapply(seq_along(levels), function(level_idx) {
      level_name <- levels[[level_idx]]
      reps <- sample_fossil_anc[[rate]][[i]][[level_name]]

      # Filter ACE matrices for each replicate
      lapply(seq_along(reps), function(rep) {
        reps[[rep]][node_v, , drop = FALSE]
      })
    })

    # Assign names to the ACE output
    names(ace_out) <- levels

    # Return the ACE matrices and the single true matrix
    return(list(ace = ace_out, true = true))
  })
})

# Assign names to the outer list
names(sample_living_nodes) <- names(continuous_matrices)


point_living_nodes <- lapply(seq_along(point_fossil_anc), function(rate) {
  lapply(seq_along(point_fossil_anc[[rate]]), function(i) {
    # Step 1: Get the node labels
    node_v <- node_labels[[i]]

    # Step 2: Get the true matrix for the current replicate
    true <- continuous_matrices[[rate]][[i]][node_v, ]

    # Step 3: Iterate over preservation levels
    levels <- names(point_fossil_anc[[rate]][[i]])
    ace_out <- lapply(levels, function(level_name) {
      # Filter ACE matrix for the current preservation level
      point_fossil_anc[[rate]][[i]][[level_name]][node_v, , drop = FALSE]
    })

    # Assign names to the ACE output
    names(ace_out) <- levels

    # Return the ACE matrices and the single true matrix
    return(list(ace = ace_out, true = true))
  })
})

# Assign names to the outer list
names(point_living_nodes) <- names(continuous_matrices)


# scaled <- lapply(nodes_living, function(preservation){
#   lapply(preservation, function(rate) {
#     lapply(rate, function(treatment) {
#       lapply(treatment, function(matrix) {
#         scaled <- scale(matrix)
#         return(scaled)
#       })
#     })
#   })
# })

scaled_point <- lapply(point_living_nodes, lapply, function(x) {
  true_scaled <- scale(x$true)  # Scale 'true' values
  
  # Extract mean and SD used for scaling
  true_center <- attr(true_scaled, "scaled:center")
  true_scale  <- attr(true_scaled, "scaled:scale")
  
  # Scale ACE levels using the same center and scale
  ace_scaled <- lapply(x$ace, function(level) {
    scale(level, center = true_center, scale = true_scale)
  })
  
  return(list(ace = ace_scaled, true = true_scaled))
})


scaled_sample <- lapply(sample_living_nodes, lapply, function(x) {
  true_scaled <- scale(x$true)
  
  # Extract the scaling parameters from true
  center <- attr(true_scaled, "scaled:center")
  scale_ <- attr(true_scaled, "scaled:scale")
  
  # Now scale each ACE replicate using the same parameters
  ace_scaled <- lapply(x$ace, function(level) {
    lapply(level, function(rep) {
      scale(rep, center = center, scale = scale_)
    })
  })
  
  return(list(ace = ace_scaled, true = true_scaled))
})
# scaled_sample <- lapply(sample_living_nodes, lapply, lapply, lapply, lapply, scale)



# nodes_living_test$bm[[1]]$fossil_high$ace[,1]
# nodes_living_test$bm[[1]]$living$ace[,1]
# nodes_living_test$bm[[1]]$fossil_high$true[,1]
# test <- sqrt(rowSums((nodes_living$bm[[5]]$all$ace - nodes_living$bm[[5]]$all$true)^2))

# nodes_living$bm[[5]]$all$ace[,1]

point_dists <- lapply(scaled_point, lapply,  function(preservation){
  ace <- preservation$ace
  true <- preservation$true
  dists <- lapply(ace, function(pres){
    distances <- sqrt(rowSums((pres - true)^2))
    median <- median(distances)
    return(distances)
  })
  return(dists)
})

# point_dists <- lapply(point_living_nodes, lapply, function(preservation) {
#   ace <- preservation$ace
#   true <- preservation$true
#   dists <- lapply(ace, function(pres) {
#     mse <- rowMeans((pres - true)^2)  # mean squared error per row
#     rmse <- sqrt(mse)                 # root mean
#     median_rmse <- median(rmse)       # median RMSE across nodes
#     return(median_rmse)
#   })
#   return(dists)
# })


sample_dists <- lapply(scaled_sample, lapply,  function(preservation){
  ace <- preservation$ace
  true <- preservation$true
  dists <- lapply(ace, function(pres){
    what <-  lapply(pres, function(rep){
      distances <- sqrt(rowSums((rep - true)^2))
      median <- median(distances)
      return(distances)
    })
  # median <- median(unlist(what))
  unlist(what)

  })
  return(dists)
})



saveRDS(point_dists, "../Data/matrices/continuous/contpointdists.Rds")
saveRDS(sample_dists, "../Data/matrices/continuous/contsampledists.Rds")


# # binded_matrices <- lapply(true_vs_ace, function(preservation) {
# #   lapply(preservation, function(rates) {
# #     lapply(rates, function(matrices) {
# #       rownames(matrices$ace) <- paste0("ace", rownames(matrices$ace))
# #       matrices <- rbind(matrices$ace, matrices$true)
# #       return(matrices)  # Return the modified matrices
# #     })
# #   })
# # })
# plot(binded_matrices$bm$fossil_low[[1]])
# text(binded_matrices$bm$fossil_low[[1]], labels = rownames(binded_matrices$bm$fossil_low[[1]]), pos = 4, cex = 0.6)

# morphospace.dist <- function(binded_matrices){
#   ace_scores <- binded_matrices[grepl("^ace", rownames(binded_matrices)), ]
#   true_scores <- binded_matrices[!grepl("^ace", rownames(binded_matrices)), ]
#   distances <- sqrt(rowSums((ace_scores - true_scores)^2))
#   return(distances)
# }

# morpho_dists <- lapply(binded_matrices, lapply, lapply, morphospace.dist)

# morpho_dists_ou <- unlist(morpho_dists$ou)

# categories <- c("living", "fossil_high", "fossil_med", "fossil_low")
# morpho_dists_ou <- split(morpho_dists_ou, gsub("\\d+", "", names(morpho_dists_ou)))
# boxplot(morpho_dists_ou, 
#         main = "", 
#         ylab = "", 
#         xlab = "Categories", 
#         las = 2)




```


## Ordinating

```{r}



proj_point <- lapply(point_living_nodes, lapply, function(x){
    true <- x$true
    ace <- x$ace
    ord_true <- prcomp(true, center = TRUE, scale. = FALSE)
    predicted <- lapply(ace, function(pres) {
      y <- predict(ord_true, newdata = pres)
    })
    return(list(true = ord_true$x, ace = predicted))
})

dispRity(proj_point$ou[[1]]$ace$living, metric = c(sum, variances))$disparity
dispRity(proj_point$ou[[2]]$true, metric = c(sum, variances))$disparity


proj_sample <- lapply(sample_living_nodes, lapply, function(x) {
    true <- x$true
    ace <- x$ace
    ord_true <- prcomp(true, center = TRUE, scale. = FALSE)
    predicted <- lapply(ace, function(pres) {
      lapply(pres, function(rep) {
        y <- predict(ord_true, newdata = rep)
      })
    })
    return(list(true = ord_true$x, ace = predicted))
})



point_ord_diff <- lapply(proj_point, lapply,  function(preservation){
  ace <- preservation$ace
  true <- preservation$true
  dists <- lapply(ace, function(pres){
    distances <- sqrt(rowSums((pres - true)^2))
    median <- median(distances)
    return(median)
  })
  return(dists)
})


sample_ord_diff <- lapply(proj_sample, lapply,  function(preservation){
  ace <- preservation$ace
  true <- preservation$true
  dists <- lapply(ace, function(pres){
    x <-  lapply(pres, function(rep){
      distances <- sqrt(rowSums((rep - true)^2))
      median <- median(distances)
      return(median)
    })
  median <- median(unlist(x))
  })
  return(dists)
})



saveRDS(point_ord_diff, "../Data/matrices/pointorddiff.Rds")
saveRDS(sample_ord_diff, "../Data/matrices/sampleorddiff.Rds")



# ---- 6. Plot with arrows ----
ggplot(df_plot) +
  geom_point(aes(x = X1, y = Y1), color = "blue", size = 3) +
  geom_point(aes(x = X2, y = Y2), color = "red", size = 3) +
  geom_segment(aes(x = X1, y = Y1, xend = X2, yend = Y2), 
               arrow = arrow(length = unit(0.2, "cm")), 
               color = "gray40") +
  geom_text_repel(aes(x = X1, y = Y1, label = Taxon), color = "blue") +
  geom_text_repel(aes(x = X2, y = Y2, label = Taxon), color = "red") +
  labs(title = "PCoA + Procrustes Alignment of Two Distance Matrices",
       x = "Axis 1", y = "Axis 2") +
  theme_minimal()


```


## Disparity
```{r}


# pca_point <- lapply(point_living_nodes, lapply, function(x){
#     true <- x$true
#     ace <- x$ace
#     ord_true <- prcomp(true)
#     ord_est <- lapply(ace, function(pres) {
#       y <- prcomp(pres)$x
#     })
#     return(list(true = ord_true$x, ace = ord_est))
# })

# pca_sample <- lapply(sample_living_nodes, lapply, function(x){
#     true <- x$true
#     ace <- x$ace
#     ord_true <- prcomp(true)
#     ord_est <- lapply(ace, function(pres) {
#       lapply(pres, function(rep){
#       y <- prcomp(rep)$x
#       })
#     })
#     return(list(true = ord_true$x, ace = ord_est))
# })

sum_var_point <- lapply(proj_point, lapply, function(matrices) {
  true_disp <- (dispRity(matrices$true, metric = c(sum, variances)))$disparity
  ace <- matrices$ace
  ace_disp <- lapply(ace, function(pres) {
    disp <- (dispRity(pres, metric = c(sum, variances)))$disparity
  })
  return(list(true = true_disp, ace = ace_disp ))
})

sum_var_sample <- lapply(proj_sample, lapply, function(matrices) {
  true_disp <- (dispRity(matrices$true, metric = c(sum, variances)))$disparity
  ace <- matrices$ace
  ace_disp <- lapply(ace, function(pres) {
    lapply(pres, function(reps) {
      disp <- (dispRity(reps, metric = c(sum, variances)))$disparity
    })
  })
  return(list(true = true_disp, ace = ace_disp ))
})



var_point_diffs <- lapply(sum_var_point, lapply, function(disparity){
  true <- disparity$true[[1]]$elements[1]
  ace <- disparity$ace
  diffs <- lapply(ace, function(pres){
    diff <- abs(pres[[1]]$elements[1] - true) /true
  })
  return(diffs)
})

var_sample_diffs <- lapply(sum_var_sample, lapply, function(disparity) {
  true <- disparity$true[[1]]$elements[1]
  ace <- disparity$ace
  diffs <- lapply(ace, function(pres) {
    lapply(pres, function(rep) {
      # Compute the difference
      diff <- abs(rep[[1]]$elements[1] - true) / true
      return(diff)
    })
  })
  
  # Apply unlist to the lowest level
  diffs <- lapply(diffs, function(pres) {
    unlist(pres, recursive = TRUE)
  })
  
  return(diffs)
})

saveRDS(var_point_diffs, "../Data/matrices/continuous/sumvarpoint.Rds")
saveRDS(var_sample_diffs, "../Data/matrices/continuous/sumvarsample.Rds")


```