---
title: "Plotting disparity curves"
author: "Caleb"
date: "`r Sys.Date()`"
output:
  html_document: default
  pdf_document: default
editor_options: 
  markdown: 
    wrap: 72
---


## Load the data

```{r}

library(ape)


sim_discrete <- readRDS( file = "../Data/processed/disparity/aceproject/simdiscrete.Rds")
beck_discrete <- readRDS( file = "../Data/processed/disparity/aceproject/beckdiscrete.Rds")
sim_discrete_anc <- readRDS( file = "../Data/processed/disparity/aceproject/simdiscreteanc.Rds")
beck_discrete_anc <- readRDS( file = "../Data/processed/disparity/aceproject/beckdiscreteanc.Rds")

sim_cont <- readRDS( file = "../Data/processed/disparity/aceproject/simcont.Rds")
sim_cont_anc <- readRDS( file = "../Data/processed/disparity/aceproject/simcontanc.Rds")
beck_cont_ <- readRDS( file = "../Data/processed/disparity/aceproject/beckcont.Rds")
beck_cont_anc <- readRDS( file = "../Data/processed/disparity/aceproject/beckcontanc.Rds")

beck_tree <- read.nexus("../Data/raw/trees/Beck2014.tre")
sim_tree <- read.tree("../Data/processed/trees/simulated.tre")

plot(beck_tree, cex = 0.7)

plot(sim_tree, cex = 0.7)
```


## Simulated tree discrete

```{r echo = FALSE}
tree_types <- c("low", "med", "high")

layout_matrix <- matrix(c(0, 1, 0, 
                          0, 2, 0, 
                          0, 3, 0),
                        nrow = 3, 
                        ncol = 3, 
                        byrow = FALSE)

layout(layout_matrix,
       heights = c(1,2,1),
       widths = c(1,1,1)
       )

for (tree in tree_types) {
    plot_title <- paste(tree)  # 
    plot(sim_discrete[[tree]]$gradual.split, main = plot_title)  # 
}

```



## Simulated tree continuous

```{r echo = FALSE}
tree_types <- c("bm", "ou", "random")

layout_matrix <- matrix(c(0, 1, 0, 
                          0, 2, 0, 
                          0, 3, 0),
                        nrow = 3, 
                        ncol = 3, 
                        byrow = FALSE)

layout(layout_matrix,
       heights = c(1,2,1),
       widths = c(1,1,1)
       )

for (tree in tree_types) {
    plot_title <- paste(tree)  # 
    plot(sim_cont[[tree]]$gradual.split, main = plot_title)  # 
}

```



## sim tree discrete (ace)

```{r echo = FALSE}
tree_types <- c("low", "med", "high")

layout_matrix <- matrix(c(0, 1, 0, 
                          0, 2, 0, 
                          0, 3, 0),
                        nrow = 3, 
                        ncol = 3, 
                        byrow = FALSE)

layout(layout_matrix,
       heights = c(1,2,1),
       widths = c(1,1,1)
       )

for (tree in tree_types) {
    plot_title <- paste(tree)  # 
    plot(sim_discrete_anc[[tree]]$gradual.split, main = plot_title)  # 
}

```

## sim tree cont (ace)

```{r echo = FALSE}
tree_types <- c("bm", "ou", "random")

layout_matrix <- matrix(c(0, 1, 0, 
                          0, 2, 0, 
                          0, 3, 0),
                        nrow = 3, 
                        ncol = 3, 
                        byrow = FALSE)

layout(layout_matrix,
       heights = c(1,2,1),
       widths = c(1,1,1)
       )

for (tree in tree_types) {
    plot_title <- paste(tree)  # 
    plot(sim_cont_anc[[tree]]$gradual.split, main = plot_title)  # 
}

```


## beck tree discrete

```{r echo = FALSE}
tree_types <- c("low", "med", "high")

layout_matrix <- matrix(c(0, 1, 0, 
                          0, 2, 0, 
                          0, 3, 0),
                        nrow = 3, 
                        ncol = 3, 
                        byrow = FALSE)

layout(layout_matrix,
       heights = c(1,2,1),
       widths = c(1,1,1)
       )

for (tree in tree_types) {
    plot_title <- paste(tree)  # 
    plot(beck_discrete[[tree]]$gradual.split, main = plot_title)  # 
}

```


## beck tree continuous

```{r echo = FALSE}
tree_types <- c("bm", "ou", "random")

layout_matrix <- matrix(c(0, 1, 0, 
                          0, 2, 0, 
                          0, 3, 0),
                        nrow = 3, 
                        ncol = 3, 
                        byrow = FALSE)

layout(layout_matrix,
       heights = c(1,2,1),
       widths = c(1,1,1)
       )

for (tree in tree_types) {
    plot_title <- paste(tree)  # 
    plot(beck_cont_[[tree]]$gradual.split, main = plot_title)  # 
}

```


## beck tree discrete (ace)

```{r echo = FALSE}
tree_types <- c("low", "med", "high")

layout_matrix <- matrix(c(0, 1, 0, 
                          0, 2, 0, 
                          0, 3, 0),
                        nrow = 3, 
                        ncol = 3, 
                        byrow = FALSE)

layout(layout_matrix,
       heights = c(1,2,1),
       widths = c(1,1,1)
       )

for (tree in tree_types) {
    plot_title <- paste(tree)  # 
    plot(beck_discrete_anc[[tree]]$gradual.split, main = plot_title)  # 
}

```

## beck tree cont (ace)

```{r echo = FALSE}
tree_types <- c("bm", "ou", "random")

layout_matrix <- matrix(c(0, 1, 0, 
                          0, 2, 0, 
                          0, 3, 0),
                        nrow = 3, 
                        ncol = 3, 
                        byrow = FALSE)

layout(layout_matrix,
       heights = c(1,2,1),
       widths = c(1,1,1)
       )

for (tree in tree_types) {
    plot_title <- paste(tree)  # 
    plot(beck_cont_anc[[tree]]$gradual.split, main = plot_title)  # 
}

```

